/*将属于标签页模块的拖到到标签页模块下*/
update ws_module t set t.parent_module_id=100011 where t.module_id in(1666,98989);

/*添加模块 子系统ATA (权限待配置)*/
insert into ws_module (ID, MODULE_ID, ORG_CODE, PARENT_MODULE_ID, MODULE_TYPE, MODULE_URL, MODULE_NAME, MODULE_PARAM, MODULE_EXPANDED, COMMON_ORDERBY, COMMON_REMARK, COMMON_AUTHOR_ID, COMMON_AUTHOR_NAME, COMMON_CREATE_TIME, COMMON_MODIFYER_NAME, COMMON_MODIFIER_ID, COMMON_MODIFY_TIME, COMMON_DISPLAY, COMMON_EXTEND_1, COMMON_EXTEND_2, COMMON_DATA_SCOPE_ID, COMMON_RECORD_STATUS, COMMON_YEAR_ON, COMMON_MONTH_ON, VIEW_ID, TABLE_ID, CHILDRENTREE_CLASS, CHILDRENTREE_METHOD, CHILDRENTREE_PARAM1, CHILDRENTREE_PARAM2, CHILDRENTREE_PARAM3, MODULE_OPEN_TYPE, MODULE_ICON, OTHER_PARAM, MODULE_NAME_ENG)
values (882, '5237', '000', '100011', 1, '', '适航审定计划-子系统ATA定义', '', 'false', '', '', '', '', '2016-10-14 15:27:45', '', '', '2016-10-14 15:27:45', 0, '', '', 0, 0, '', '', '', '', '', '', '', '', '', 0, '', '', '');

/*添加模块 子系统试验清单 (权限待配置)*/
update ws_module t set t.module_id=1668 where t.module_id=1666;
insert into ws_module (ID, MODULE_ID, ORG_CODE, PARENT_MODULE_ID, MODULE_TYPE, MODULE_URL, MODULE_NAME, MODULE_PARAM, MODULE_EXPANDED, COMMON_ORDERBY, COMMON_REMARK, COMMON_AUTHOR_ID, COMMON_AUTHOR_NAME, COMMON_CREATE_TIME, COMMON_MODIFYER_NAME, COMMON_MODIFIER_ID, COMMON_MODIFY_TIME, COMMON_DISPLAY, COMMON_EXTEND_1, COMMON_EXTEND_2, COMMON_DATA_SCOPE_ID, COMMON_RECORD_STATUS, COMMON_YEAR_ON, COMMON_MONTH_ON, VIEW_ID, TABLE_ID, CHILDRENTREE_CLASS, CHILDRENTREE_METHOD, CHILDRENTREE_PARAM1, CHILDRENTREE_PARAM2, CHILDRENTREE_PARAM3, MODULE_OPEN_TYPE, MODULE_ICON, OTHER_PARAM, MODULE_NAME_ENG)
values (842, '1666', '000', '100011', 1, 'singlereportext/list.dd', '适航审定计划-子系统试验清单', '', 'false', '0072', '', '', '', '', '', '', '2016-10-16 15:18:14', 0, '', '', 0, 0, '', '', '', '', '', '', '', '', '', 0, '', '', '');

/*添加模块 项目符合性检查清单 (权限待配置)*/
insert into ws_module (ID, MODULE_ID, ORG_CODE, PARENT_MODULE_ID, MODULE_TYPE, MODULE_URL, MODULE_NAME, MODULE_PARAM, MODULE_EXPANDED, COMMON_ORDERBY, COMMON_REMARK, COMMON_AUTHOR_ID, COMMON_AUTHOR_NAME, COMMON_CREATE_TIME, COMMON_MODIFYER_NAME, COMMON_MODIFIER_ID, COMMON_MODIFY_TIME, COMMON_DISPLAY, COMMON_EXTEND_1, COMMON_EXTEND_2, COMMON_DATA_SCOPE_ID, COMMON_RECORD_STATUS, COMMON_YEAR_ON, COMMON_MONTH_ON, VIEW_ID, TABLE_ID, CHILDRENTREE_CLASS, CHILDRENTREE_METHOD, CHILDRENTREE_PARAM1, CHILDRENTREE_PARAM2, CHILDRENTREE_PARAM3, MODULE_OPEN_TYPE, MODULE_ICON, OTHER_PARAM, MODULE_NAME_ENG)
values (884, '98999', '000', '100011', 1, 'caaw/caaw_configurable_treetable/viewTreeTable.dd', '适航审定计划-项目符合性检查清单', '', 'false', '0071', '', '', '', '', '', '', '2016-10-16 16:19:47', 0, '', '', 0, 0, '', '', '', '', '', '', '', '', '', 0, '', '', '');

/*添加模块 项目符合性方法 (权限待配置)*/
insert into ws_module (ID, MODULE_ID, ORG_CODE, PARENT_MODULE_ID, MODULE_TYPE, MODULE_URL, MODULE_NAME, MODULE_PARAM, MODULE_EXPANDED, COMMON_ORDERBY, COMMON_REMARK, COMMON_AUTHOR_ID, COMMON_AUTHOR_NAME, COMMON_CREATE_TIME, COMMON_MODIFYER_NAME, COMMON_MODIFIER_ID, COMMON_MODIFY_TIME, COMMON_DISPLAY, COMMON_EXTEND_1, COMMON_EXTEND_2, COMMON_DATA_SCOPE_ID, COMMON_RECORD_STATUS, COMMON_YEAR_ON, COMMON_MONTH_ON, VIEW_ID, TABLE_ID, CHILDRENTREE_CLASS, CHILDRENTREE_METHOD, CHILDRENTREE_PARAM1, CHILDRENTREE_PARAM2, CHILDRENTREE_PARAM3, MODULE_OPEN_TYPE, MODULE_ICON, OTHER_PARAM, MODULE_NAME_ENG)
values (902, '1677', '000', '100011', 1, '', '适航审定计划-子系统符合性方法', '', 'false', '', '', '', '', '2016-10-19 20:29:27', '', '', '2016-10-19 20:29:27', 0, '', '', 0, 0, '', '', '', '', '', '', '', '', '', 0, '', '', '');

/*添加模块 子系统符合性方法 (权限待配置)*/
insert into ws_module (ID, MODULE_ID, ORG_CODE, PARENT_MODULE_ID, MODULE_TYPE, MODULE_URL, MODULE_NAME, MODULE_PARAM, MODULE_EXPANDED, COMMON_ORDERBY, COMMON_REMARK, COMMON_AUTHOR_ID, COMMON_AUTHOR_NAME, COMMON_CREATE_TIME, COMMON_MODIFYER_NAME, COMMON_MODIFIER_ID, COMMON_MODIFY_TIME, COMMON_DISPLAY, COMMON_EXTEND_1, COMMON_EXTEND_2, COMMON_DATA_SCOPE_ID, COMMON_RECORD_STATUS, COMMON_YEAR_ON, COMMON_MONTH_ON, VIEW_ID, TABLE_ID, CHILDRENTREE_CLASS, CHILDRENTREE_METHOD, CHILDRENTREE_PARAM1, CHILDRENTREE_PARAM2, CHILDRENTREE_PARAM3, MODULE_OPEN_TYPE, MODULE_ICON, OTHER_PARAM, MODULE_NAME_ENG)
values (903, '1678', '000', '100011', 1, '', ' 适航审定计划-项目符合性方法', '', 'false', '', '', '', '', '2016-10-19 20:31:11', '', '', '2016-10-19 20:31:11', 0, '', '', 0, 0, '', '', '', '', '', '', '', '', '', 0, '', '', '');


/*文件名称*/
update ws_dataitem t set t.onclick='' where t.dataitem_id=1338;

/*添加模块 条款符合性说明报告 (权限待配置)*/
insert into ws_module (ID, MODULE_ID, ORG_CODE, PARENT_MODULE_ID, MODULE_TYPE, MODULE_URL, MODULE_NAME, MODULE_PARAM, MODULE_EXPANDED, COMMON_ORDERBY, COMMON_REMARK, COMMON_AUTHOR_ID, COMMON_AUTHOR_NAME, COMMON_CREATE_TIME, COMMON_MODIFYER_NAME, COMMON_MODIFIER_ID, COMMON_MODIFY_TIME, COMMON_DISPLAY, COMMON_EXTEND_1, COMMON_EXTEND_2, COMMON_DATA_SCOPE_ID, COMMON_RECORD_STATUS, COMMON_YEAR_ON, COMMON_MONTH_ON, VIEW_ID, TABLE_ID, CHILDRENTREE_CLASS, CHILDRENTREE_METHOD, CHILDRENTREE_PARAM1, CHILDRENTREE_PARAM2, CHILDRENTREE_PARAM3, MODULE_OPEN_TYPE, MODULE_ICON, OTHER_PARAM, MODULE_NAME_ENG)
values (904, '43008', '000', '100011', 1, 'singlereportext/list.dd', '适航审定计划-条款符合性说明报告', '', 'false', '', '', '', '', '', '', '', '2016-10-21 11:38:03', 0, '', '', 0, 0, '', '', '', '', '', '', '', '', '', 0, '', '', '');


/*将条款符合性说明报告（594）和条款FC ATA（624）合并为同一张表 624作废*/
update ws_dataitem t set t.domain_id=742 where t.dataitem_id in(3200,3208,3210);
update ws_dataitem t set t.dataitem_name='条款ID' where t.dataitem_id=3210;

/*select * from ws_module t where t.module_id=43008*/


/*更新当前库脚本编号*/
 update ws_sys set par_value='186', common_modify_time=to_char(sysdate,'yyyy-MM-dd HH24:mi:ss')
   where par_name='DB_VERSION';
commit;
