	    /** 用户关系表 */
  CREATE TABLE WS_USER_RELATION(
		  ID                NUMBER NOT NULL,
		  TD_ID           NUMBER NOT NULL,
		  RE_TD_ID NUMBER NOT NULL,
		  RELATION VARCHAR2(100),
      RELATION_DESC VARCHAR2(1024),
		  COMMON_ORDERBY       VARCHAR2(100),
		  COMMON_REMARK        VARCHAR2(1024),
		  COMMON_AUTHOR_ID     VARCHAR2(100),
		  COMMON_AUTHOR_NAME   VARCHAR2(100),
		  COMMON_CREATE_TIME   VARCHAR2(100),
		  COMMON_MODIFYER_NAME VARCHAR2(100),
		  COMMON_MODIFIER_ID   VARCHAR2(100),
		  COMMON_MODIFY_TIME   VARCHAR2(100),
		  COMMON_DISPLAY       INTEGER DEFAULT 1,
		  COMMON_EXTEND_1      VARCHAR2(1024),
		  COMMON_EXTEND_2      VARCHAR2(1024),
		  COMMON_DATA_SCOPE_ID INTEGER DEFAULT 0,
		  COMMON_RECORD_STATUS INTEGER DEFAULT 1,
		  COMMON_YEAR_ON       VARCHAR2(100),
		  COMMON_MONTH_ON      VARCHAR2(100),
		  CONSTRAINT PK_WS_USER_RELATION PRIMARY KEY (ID)
		);

		/** CREATE SEQUENCE */
		CREATE SEQUENCE SEQ_WS_USER_RELATION
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCACHE;