/*重新创建自动发起流程的相关表，去除岗位之后，将原接收部门改为接收人*/	
DROP TABLE WS_V2_PROCESSSTARTJOBCONFIG;
	CREATE TABLE WS_V2_PROCESSSTARTJOBCONFIG
	(
	  VERSION NUMBER NOT NULL,
	  TRIGGER_NAME VARCHAR2(4000),
	  ACCEPT_USER CLOB,
	  CHILD_ACCEPT_USER CLOB,
	  MODULE_ID VARCHAR2(1024),
	  TITLE VARCHAR2(4000),
	  CONTENT CLOB,
	  SL_ID VARCHAR2(4000),
	  HAS_CHILD VARCHAR2(20),
	  CHILD_FLOWNAME VARCHAR2(4000),
	  CHILD_DEPT_ID CLOB,
	  CHILD_DEPT_NAME CLOB,
	  CURRENT_DATE_PARAM VARCHAR2(1024),
	  CHILD_CURRENT_DATE_PARAM VARCHAR2(1024),
	  CONSTRAINT PK_V2_PROCESSSTART PRIMARY KEY (TRIGGER_NAME) 
	);