
package com.alison.webservice.test;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MyWebServiceImplService", targetNamespace = "http://impl.service.webservice.alison.com/", wsdlLocation = "http://localhost:8080/valison/MyService?wsdl")
public class MyWebServiceImplService
    extends Service
{

    private final static URL MYWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.alison.webservice.test.MyWebServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.alison.webservice.test.MyWebServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/valison/MyService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/valison/MyService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MYWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public MyWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyWebServiceImplService() {
        super(MYWEBSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://impl.service.webservice.alison.com/", "MyWebServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns MyWebServiceImpl
     */
    @WebEndpoint(name = "MyWebServiceImplPort")
    public MyWebServiceImpl getMyWebServiceImplPort() {
        return super.getPort(new QName("http://impl.service.webservice.alison.com/", "MyWebServiceImplPort"), MyWebServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyWebServiceImpl
     */
    @WebEndpoint(name = "MyWebServiceImplPort")
    public MyWebServiceImpl getMyWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.webservice.alison.com/", "MyWebServiceImplPort"), MyWebServiceImpl.class, features);
    }

}
